import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bonheur_Royale, Montserrat, Anton } from "next/font/google";


const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",   // Anton only has one weight
});


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


const bonheurRoyale = Bonheur_Royale({
  variable: "--font-bonheur-royale",
  subsets: ["latin"],
  weight: "400",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bonheurRoyale.variable} ${montserrat.variable} ${anton.variable} h-full antialiased`} >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
